### PR TITLE
Update the index and outline for fall 2023.

### PR DESCRIPTION
**Pull request by jdelamer**
### What
Update the professor information for Fall 2023.

### Why
James is not teaching the section of Fall 2023.

### Where
Changes are in index.rst and outline.rst

### CODE REVIEW

**Review by jameshughes89 — COMMENTED** [review]
I suggest removing this. Sadly, no one used it and it just created more work for everyone.

**Review by jameshughes89 — APPROVED** [review]

**Comment by jdelamer** [comment]
I added office hours and removed recoupment.

**Review by jameshughes89 — APPROVED** [review]
If you want to add the stuff that was circulated recently, have a look here https://github.com/jameshughes89/cs101/pull/569. You can copy/paste a lot of it (it will reduce the amount of suffering you need to go through).

**Review by jameshughes89 — APPROVED** [review]
:rocket:

**Pull request merged**
