### PR TITLE
:new: Update Gradle Version

### PR DESCRIPTION
**Pull request by jameshughes89**
### What
Update Gradle

### Why
The version I was using stopped doing some things. This issue happened a while ago on only one comp, but since I started using it today, I opted to figure out the issue. 

### How
Some dude on the internet said this should do the trick

### Testing
Yeah --- dude on the internet seems to be right.

### CODE REVIEW

**Review by twentylemon — COMMENTED** [review]
This doesn't really look like a gradle upgrade.

https://docs.gradle.org/current/userguide/upgrading_version_6.html

**Comment by jameshughes89** [comment]
> This doesn't really look like a gradle upgrade.
> 
> https://docs.gradle.org/current/userguide/upgrading_version_6.html

[It looks like it is an "official" way to do it](https://www.jetbrains.com/help/idea/gradle-settings.html) --- see "Use Gradle from"

also links to this [wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)

**Comment by twentylemon** [comment]
Use the gradle docs, not intellij. Running the upgrade locally for me yields:

```
lemon@lemonade:~/git/cs102$ git df
warning: CRLF will be replaced by LF in gradlew.bat.
The file will have its original line endings in your working directory
 gradle/wrapper/gradle-wrapper.jar        | Bin 59203 -> 59536 bytes
 gradle/wrapper/gradle-wrapper.properties |   2 +-
 gradlew                                  | 257 ++++++++++++++++++++++++++++++++++++++++++-----------------------------
 3 files changed, 154 insertions(+), 105 deletions(-)
```

**Comment by jameshughes89** [comment]
RE issues discussed offline, verify jdk `sudo apt-get install openjdk-11-jdk`

**Pull request closed without merging**
