### PR TITLE
:mortar_board: Topic19 Breaking down problems and going 'up' vs 'down'

### PR DESCRIPTION
**Pull request by jameshughes89**
### What
- Add points about breaking the problem down over and over again 
    - Add point about how it may feel like cheating, but really we keep applying the same thing over and over
-  Add examples of going 'up' and 'down' (for lack of better terms)

### Additional Notes
Breaking this section into mulriple PRs.

### CODE REVIEW

**Review by twentylemon — CHANGES_REQUESTED** [review]
"Up" and "down" are "tail" and "head" recursion. Probably better to use the actual terms.

https://stackoverflow.com/questions/21426688/the-difference-between-head-tail-recursion

**Comment by jameshughes89** [comment]
> "Up" and "down" are "tail" and "head" recursion. Probably better to use the actual terms.
> 
> https://stackoverflow.com/questions/21426688/the-difference-between-head-tail-recursion

I don't think they're quite the same thing here since I believe _tail_ and _head_ are more about the structure of the recursive function, where here I am using _up_ and _down_ to mean moving towards or away from a base case.

**Comment by twentylemon** [comment]
> I don't think they're quite the same thing here since I believe _tail_ and _head_ are more about the structure of the recursive function, where here I am using _up_ and _down_ to mean moving towards or away from a base case.

I see, I misunderstood then. In this case, I don't even think it's worth mentioning or creating terms for it. No matter what, the recursion is defined by base cases and recursive cases, there's no directionality to it.

I also find the example confusing. Going _up_ you are making conclusions, going _down_ you are asking questions (and invoking the tail recursion...). It even states in the going _down_ portion
> Zero is a natural number, therefore they're all natural numbers

Which means you suddenly started going _up_ again.

**Comment by jameshughes89** [comment]
> > I don't think they're quite the same thing here since I believe _tail_ and _head_ are more about the structure of the recursive function, where here I am using _up_ and _down_ to mean moving towards or away from a base case.
> 
> I see, I misunderstood then. In this case, I don't even think it's worth mentioning or creating terms for it. No matter what, the recursion is defined by base cases and recursive cases, there's no directionality to it.
> 
> I also find the example confusing. Going _up_ you are making conclusions, going _down_ you are asking questions (and invoking the tail recursion...). It even states in the going _down_ portion
> 
> > Zero is a natural number, therefore they're all natural numbers
> 
> Which means you suddenly started going _up_ again.

Good point. I'll think on reworking this bit a tad.

**Review by twentylemon — APPROVED** [review]

**Pull request merged**
