### PR TITLE
:memo: Update and change emojies to correspond to labels

### LINKED ISSUE #85: :memo: Add additional emojis for labels
### Issues or PRs
Related #28 #83 #81

### What 
Add additional emojis and update emoji descriptions to be 1:1 with [labels](https://github.com/jameshughes89/cs102/issues/labels).

### Why
This lets people self label/tag their issues & PRs mor eeffectively 

### Where
Changes will need to be made in CONTRUBITING.md's style guide section

### PR DESCRIPTION
**Pull request by jameshughes89**
### Issues or PRs
Closes #85 

### What
Changing out the emojies to relate to the labels. Some labels were changed and removed from repo. 

### Why
This allows people contributing to self tag their PRs and Issues

### CODE REVIEW

**Comment by twentylemon** [comment]
Imo, change the label names to match the emojis, or to include the emoji name in it. For this one for example, it's not wholly clear that `:memo: <=> documentation`. But that'd probably be fine if it were `documentation/:memo:`.

**Comment by jameshughes89** [comment]
I love this idea

> Imo, change the label names to match the emojis, or to include the emoji name in it. For this one for example, it's not wholly clear that `:memo: <=> documentation`. But that'd probably be fine if it were `documentation/:memo:`.

I love this idea.

**Comment by jameshughes89** [comment]
Check it our dude --- https://github.com/jameshughes89/cs102/issues/labels

**Comment by twentylemon** [comment]
From DC:

> man. unfortunately they are not searchable still
like, clicking labels on a PR then typing "memo" doesn't give me documentation
maybe `documentation/memo :memo:` ?

**Review by twentylemon — APPROVED** [review]
LGTM

**Pull request merged**
