### PR TITLE
🎓 🔭 "as many.. you need" -> "as many.. as you need"

### PR DESCRIPTION
**Pull request by KurtisCruikshank**
### What
Add "as" to the specified sentence

### Why
Looks funky otherwise

### Where
Assignment #3, under Part 4 "Implementing the Class"

### How
Type it

### CODE REVIEW

**Comment by jameshughes89** [comment]
I need a 2nd set of eyes on this. I am not sure if it _actually_ is more correct that way.

**Review by jameshughes89 — APPROVED** [review]
Confirmed with an expert that the correction makes it more correct.

**Comment by twentylemon** [comment]
> Confirmed with an expert

I didn't reply though.

**Comment by jameshughes89** [comment]
> > Confirmed with an expert
> 
> I didn't reply though.

Ohhh, youuuuuuu

**Pull request merged**
