### PR TITLE
:telescope: :technologist: `ArrayQueue` --- Change `++i` -> `i++` :microscope: 

### PR DESCRIPTION
**Pull request by jameshughes89**
### What
Change `++i` to `i++` in the for loops

### Why
1. consistency
2. People always bring it up (like what was just done in lecture) and it distracts from the actual content. 

### Testing
:+1:

### CODE REVIEW

**Review by twentylemon — COMMENTED** [review]
!mock my performance

**Comment by jameshughes89** [comment]
> !mock my performance

**Comment by jameshughes89** [comment]
i hit a bad button

**Comment by twentylemon** [comment]
image

**Comment by jameshughes89** [comment]
I was worried about my nano seconds

**Comment by jameshughes89** [comment]
https://www.youtube.com/watch?v=tKbV6BpH-C8&t=273s

**Review by twentylemon — APPROVED** [review]
(meant to approve originally)

**Pull request merged**
